name: iOSCI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    name: Build and Test iPhone
    runs-on: macOS-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     - uses: actions/checkout@v2
     - name: List available Xcode versions
       run: ls /Applications | grep Xcode

     # Runs a single command using the runners shell
     - name: Run a one-line script
       run: sudo xcode-select -switch /Applications/Xcode_12.1.app && /usr/bin/xcodebuild -version
     - name: Install Dependencies
       run: |
         cd TheMovieTime
         pod repo update
     # Runs a set of commands using the runners shell
     - name: Run a multi-line script
       run: |
          cd TheMovieTime && ls
          xcodebuild test -workspace NewMovieTime.xcworkspace -scheme TheMovieTime -destination "platform=iOS Simulator,name=iPhone 11,OS=15.0"
